package lk.ijse.finalwithlayered.navigation;

public enum Routes {
    LOGIN,HOME,CUSTOMER,PLACE_ORDER,EMPLOYEE,RAW_MATERIAL,ATTENDANCE,SALARY,SUPPLIER,LOGOUT,ADD_CUSTOMER,UPDATE_CUSTOMER,ADD_EMPLOYEE,UPDATE_EMPLOYEE,ADD_SUPPLIER,UPDATE_SUPPLIER
}
